--alter session set current_schema=DW_DATA;
--drop table t_dw_fct_orders;

alter session set current_schema=DW_DATA;

Create table t_dw_fct_orders (
order_id                      INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
client_id                     INT              not null,
doer_id                       INT              not null,
region_id                     INT              not null,
currenci_id                   INT              not null,
date_id                       INT              not null,
employee_id                   INT              not null,
product_name                  VARCHAR2(15)     not null,
order_price                   FLOAT            not null,
order_status                  VARCHAR2(15)     not null,
order_date                    DATE             not null,
receiving_date                VARCHAR2(15)     not null,
payment_method                VARCHAR2(15)     not null,
constraint PK_T_DW_ORDERS primary key (order_id)
);

ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_customers_t_dw_fct_orders FOREIGN KEY (client_id)
      REFERENCES DW_DATA.t_dw_customers (client_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_customers_t_dw_orders;
   */
      
ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_doers_t_dw_fct_orders FOREIGN KEY (doer_id)
      REFERENCES DW_DATA.t_dw_doers (doer_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_doers_t_dw_fct_orders;
   */

ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_regions_t_dw_fct_orders FOREIGN KEY (region_id)
      REFERENCES DW_DATA.t_dw_regions (region_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_regions_t_dw_fct_orders;
   */
      
ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_currencies_t_dw_fct_orders FOREIGN KEY (currenci_id)
      REFERENCES DW_DATA.t_dw_currencies (currenci_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_currencies_t_dw_fct_orders;
   */
      
ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_accountings_t_dw_fct_orders FOREIGN KEY (date_id)
      REFERENCES DW_DATA.t_dw_accounting (date_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_accountings_t_dw_fct_orders;
   */
      
ALTER TABLE DW_DATA.t_dw_fct_orders
   ADD CONSTRAINT fk_t_dw_employees_t_dw_fct_orders FOREIGN KEY (employee_id)
      REFERENCES DW_DATA.t_dw_employees (employee_id);
      
/*
ALTER TABLE DW_DATA.t_dw_fct_orders
   DROP CONSTRAINT fk_t_dw_employees_t_dw_fct_orders;
   */